version: '3.9'
services:
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=pippo
    ports:
      - 3307:3306

  php-apache-environment:
    container_name: php-apache-2
    build: .
    ports:
      - 8004:80
    volumes:
      - ./php/src:/var/www/html/
    depends_on:
      - phpmyadmin
      - mariadb
